# ========= global settings ===================================================
is_fullscreen: &fullscreen false
show_progress_bar: false
screenwidth: 1024
fontsize: &fontsize 20px
remove_prompt_below: &rr false
true_random: &tr true
prob_win: &pw .6

# ========= osf/datapipe/prolific settings ======================================
osf_id: UyAz4Ynp2fVS
prolific_id: 84F912E7
pipe_data_to_osf: true

# ========= practice settings ===================================================
practice_trial_rounds: &ptr 2
practice_trial_time: &ptt 5
show_practice_result: &pts false
number_of_history_keypress: &nhk 4

# ========= bonus settings ======================================================
bonus_trial_rounds: &btr 20
bonus_target_minimum: &btm 1
quantile_practice_scores_as_target:  &qpt 100 #use maximum
time:
  bonus_trial_time: &btt 5
  fixation_duration: &ffd 2
  feedback_score_time: &fst 2
  feedback_bonus_time: &fbt 3
target_number_dist: &btd 
  choice: uniform
  quantile: *qpt
  normal: {std: 20}
  uniform: {range: 20}
stop_when_pass_target: &swpt false

# ========= thank you message ===================================================
thank_you_msg: >
  <div align='center' style="margin: 10%">
      <p>Thank you for participating!</p>
      <p>In total, you won <b>$${totalBonus}</b> tokens!</p>
      <br>
      <p>Within one week, you'll find out if you won the $100.00 bonus.</p>
      <b>Please wait to be re-directed to Prolific.</b>
  </div>

# ========= stimulus simulation =================================================
list_of_available_pair_keys: &llll 
  - d,k
  - f,j
  - t,u

# fullscreen
fullscreen:
  type: fullscreen
  fullscreen_mode: *fullscreen # doesn't work in MAC
  message: <p>The experiment will switch to full screen mode when you press the button below</p>

# practice round
practice:
  numOfTrial: *ptr
  trial_duration: *ptt
  num_keypress_display: *nhk
  fixation_duration: *ffd #2 sec for guideline and 1 sec for fixation
  fontsize: *fontsize  #fontsize of displayed stimulus
  no_prompt: *rr
  show_stat: *pts
  data: 
    phase: practice
  list: *llll
  true_random: *tr
  prob_win: *pw

bonus_feedback_main: &bfm >
  <div class="bonus-1" style="margin: 40px 0px">
    <div class="bonus-2">
      <div class="bonus-3">Your score:</div>
      <div class="bonus-4"><span id="current-number">62</span></div>
    </div>
    <div class="bonus-2">
      <div class="bonus-3">Target score:</div>
      <div class="bonus-4" style="color: red"><span id="target-number">50</span></div>
    </div>
  </div>

bonus_feedback_success: &bfs >
  <div class="bonus-1" id="feedback">
    <div class="bonus-2">
      You reached the target score!
    </div>
    <div class="bonus-2">
      <div id="bonus-number"></div>
    </div>
  </div>

bonus_feedback_failure: &bff >
  <div class="bonus-1" id="feedback">
    <div class="bonus-2">
      You missed the target score!
    </div>
    <div class="bonus-2">
      <div id="bonus-number"></div>
    </div>
  </div>


bonus:
  numOfTrial: *btr
  target_dist: *btd
  target_min: *btm
  fontsize: *fontsize
  no_prompt: *rr
  time:
    trial_time: *btt
    fix_time: *ffd
    score_time: *fst
    reward_time: *fbt
  data: 
    phase: bonus
  list: *llll
  feedback:
    main_feedback: *bfm
    success_feedback: *bfs
    failure_feedback: *bff
  early_stop: *swpt
  true_random: *tr
  prob_win: *pw


# preload images
images_to_preload:
  type: preload
  data: 
    phase: preload
  images:
    - 

# consent pages

consent_page: &p1 >
  <div class='instruction'>
    <h2 class='jspsych-content'>Research Information Sheet – Behavioral Lab</h2>
    <p><strong>Vanderbilt University</strong><br>
    Department: Marketing<br>
    Principal Investigator: Jackie Silverman, PhD</p>

    <h3>Introduction</h3>
    <p>You are being asked to take part in a research study.</p>

    <h3>Who is doing this research study?</h3>
    <p>The person in charge of this research study is Dr. Jackie Silverman of Vanderbilt University Department of Marketing.</p>

    <h3>What is the purpose of this research study?</h3>
    <p>The purpose of this research is to understand how people make decisions.</p>

    <h3>Who will be in this research study?</h3>
    <p>You must be at least 18 years of age and able to understand English to participate.</p>

    <h3>What will you be asked to do in this research study, and how long will it take?</h3>
    <p><strong>Description:</strong> You will complete a short survey. In this survey, you may be asked to evaluate your feelings and opinions towards a variety of different people, places, or events. Please note that you will be randomly assigned (which is like flipping a coin) to one of two scenarios in the survey. Participants in each group receive different scenarios. If you have any questions or concerns, let the research team know.</p>
    <p><strong>Eligibility requirements:</strong> You must be 18 or older to participate in this research study and able to read English at a proficient level.</p>
    <p><strong>Compensation:</strong> Compensation will be set at the amount of $2.70.</p>

    <h3>Are there any risks to being in this research study?</h3>
    <p>There may be a possible risk of loss of confidentiality and every effort will be made to protect confidentiality of the data.</p>

    <h3>Are there any benefits from being in this research study?</h3>
    <p>You will not directly benefit from participating in this research.</p>

    <h3>Do you have choices about taking part in this research study?</h3>
    <p>If you do not want to take part in this research study, you are welcome to exit now or to not continue at any time.</p>

    <h3>How will your research information be kept confidential?</h3>
    <p>No identifying information will be collected in this survey. The data from this research may be published; but the information you provide will be pooled with all respondents and reported in aggregate. In some cases, de-identified data may be made publicly available on platforms such as the Open Science Framework. Representatives of Vanderbilt University may inspect study records for audit or quality assurance purposes.</p>

    <h3>Additional confidentiality details</h3>
    <p>All efforts, within reason, will be made to keep your personal information in your research record confidential but total confidentiality cannot be guaranteed. The data will be stored in secure files accessible only to Dr. Jackie Silverman and trained research assistants. Each participant in the study will have a code number. Your name and other identifying information about you will not be used in the research. After the research is completed, we may save de-identified data for use in future research.</p>

    <h3>Study Results</h3>
    <p>Study results will not be made available to participants at this time.</p>

    <h3>Circumstances under which the Principal Investigator may withdraw you from study participation</h3>
    <p>You may be withdrawn from the study if you fail a question checking for attention.</p>

    <h3>What happens if you choose to withdraw from study participation?</h3>
    <p>Nothing.</p>

    <h3>Contact Information</h3>
    <p>If you have any questions about the research, you may email Jackie.Silverman@Vanderbilt.edu. For additional information about your rights as a participant in this study, to discuss problems, concerns, and questions, or to offer input, please contact the Vanderbilt University Social Behavioral Educational Research Institutional Review Board (VU SBER IRB) at irb@vanderbilt.edu.</p>
  </div>


consent:
  type: checkbox
  data: 
    phase: consent
  questions:
    - prompt: *p1
      timing_post_trial: 0
      options: ["I have read this informational sheet, and I freely and voluntarily choose to participate. By proceeding, you agree to participate in this study. If you do not wish to participate, please close your browser now."]
      required: true
  required_message: To proceed to the experiment, please ensure that you have checked the checkbox
  button_label: Next


practice_p0: &p0 >
  <div class='instruction'> 
  <p><strong>What makes some activities more immersive and engaging than others?</strong></p>
  <p>We're interested in why people feel effortlessly engaged in some activities (such as engrossing video games), but struggle to focus on other activities (like tedious chores).</p>
  <p>To help us, you'll complete two different versions of a <strong>typing task</strong>. After each version, you'll report how immersed and engaged you felt.</p>
  <p>When you're ready to learn about the first version of the typing task, continue to the next page.</p>
  </div>

practice_p1: &p1 >
  <div class='instruction'> 
  <p>The first version of the typing task takes place over multiple rounds.</p>
  <p>In each round, you'll type two letters—one after the other—as many times as possible in the allotted time. </p>
  <p>For each correct letter you press in sequence, your score will increase by one.</p>
  <p>For instance, if your task is to type <span id=keystroke>a</span> then <span id=keystroke>b</span>, and you type <span id=keystroke>a</span><span id=keystroke>b</span><span id=keystroke>a</span><span id=keystroke>b</span><span id=keystroke>x</span>, your score will increase by <b>4</b>. However, if you type <span id=keystroke>a</span><span id=keystroke>a</span><span id=keystroke>a</span><span id=keystroke>a</span><span id=keystroke>x</span> your score will increase by <b>1</b>.</p>
  <p>We recommend using your two index fingers to type.</p>
  <img src="https://raw.githubusercontent.com/dennislx/jspsych-typing/main/public/img/instr-keyboard.png" id="keypress-img">
  </div>

practice_p2: &p2 >
  <div class='instruction'> 
  <p>To get a feel for the first version of the typing task, you'll complete multiple <b>practice</b> rounds. During the practice rounds, your goal is to type the letters as many times as possible during the allotted time.</p>
  <p>Press the <span class="jspsych-btn">Next ></span> button to start practing.</p>
  </div>


practice_instruction:
  type: instruct
  pages:
    - *p0
    - *p1
    - *p2
  show_clickable_nav: true
  show_page_number: true
  data: 
    phase: practice_instruction


bonus_welcome_1: &i1 >
  <div class="instruction">
  <p>Practice is now complete. Soon, you'll complete the first version of the typing task.</p>
  <p><b>During the first version of the typing task, you'll compete for a $100.00 bonus!</b></p>
  <p>Specifically, during the first version of the typing task, you'll earn tokens. The tokens you earn will be entered into a lottery, and if one of your tokens is drawn, you'll win $100.00. Therefore, to maximize your chances of winning a $100.00 bonus, you'll need to earn as many tokens as possible.</p>
  <p>To learn how to earn tokens, continue to the next screen.</p>
  </div>

bonus_welcome_1_2: &i1_2 >
  <div class="instruction">
  <p>Thank you for completing the first version of the typing task! Next, you'll complete the second version of the typing task.</p>
  <p><b>The second version of the typing task is just like the first version, except the rules for earning tokens are different.</b></p>
  <p>To learn how to earn tokens in the second version of the typing task, continue to the next screen.</p>
  </div>

bonus_welcome_2: &i2 >
  <div class="instruction">
  <p>During the first version of the typing task, each round will have a different <b>target score</b>. 
  If you reach the target score before time runs out, the round will be marked as "complete."</p>
  <p>For example, if the target score is 50, a score of 50 or more is needed to complete the round.</p>
  <p>The target score is not revealed until the end of each round.</p>
  <p>${instruction_by_group}</p>
  <p>For an illustration of the first version of the typing task, continue to the next screen.</p>
  </div>

bonus_welcome_2_2: &i2_2 >
  <div class="instruction">
  <p>${instruction_by_group}</p>
  <p>For an illustration of the second version of the typing task, continue to the next screen.</p>
  </div>

i_binary_streak: &ig1 >
  In the first version of the typing task, tokens are awarded for <b>streaks of three consecutive completions</b>. Specifically, each time you complete <b>three consecutive rounds</b>, you'll earn <b>60 tokens</b>. 

i_continuous_streak: &ig2 >
  In the first version of the typing task, tokens are awarded for <b>streaks of consecutive completions</b>. Specifically, for <b>every consecutive round you complete</b>, you'll earn <b>20 tokens</b>. 

i_binary_framing: &ig3 >
  In the first version of the typing task, tokens are awarded for <b>each individual completion</b>. For <b>each individual round you complete</b>, you'll earn <b>20 tokens</b>. 

i_inverse_framing: &ig4 >
  In the first version of the typing task, tokens are awarded for achieving completions in <b>as few attempts as possible</b>. For each round you complete, you'll earn <b>30 tokens minus {tokens} for every attempt you took to achieve the completion</b>. 

i_binary_streak_2: &ig1_2 >
  In the second version of the typing task, tokens are awarded for <b>streaks of three consecutive completions</b>. Specifically, each time you complete <b>three consecutive rounds</b>, you'll earn <b>60 tokens</b>. 

i_continuous_streak_2: &ig2_2 >
  In the second version of the typing task, tokens are awarded for <b>streaks of consecutive completions</b>. Specifically, for <b>every consecutive round you complete</b>, you'll earn <b>20 tokens</b>. 

i_binary_framing_2: &ig3_2 >
  In the second version of the typing task, tokens are awarded for <b>each individual completion</b>. For <b>each individual round you complete</b>, you'll earn <b>20 tokens</b>. 

i_inverse_framing_2: &ig4_2 >
  In the second version of the typing task, tokens are awarded for achieving completions in <b>as few attempts as possible</b>. For each round you complete, you'll earn <b>30 tokens minus {tokens} for every attempt you took to achieve the completion</b>. 


bonus_survey_question1: &q1
  prompt: To complete a round, you must press the two keys…
  options: 
    - 10 times
    - 30 times
    - At least as many times as the target score (which is not revealed until the end of the round)
    - Exactly as many times as the target score (which is not revealed until the end of the round)

bonus_survey_question2: &q2
  prompt: If you complete the first two rounds in a row, then fail to complete the third round, you will have earned…
  options:
    - 0 tokens
    - 20 tokens
    - 40 tokens
    - 60 tokens

bonus_survey_question3: &q3
  prompt: If you complete the first three rounds in a row, then fail to complete the fourth round, you will have earned…
  options:
    - 0 tokens
    - 20 tokens
    - 40 tokens
    - 60 tokens

bonus_survey_question2_inv: &q2_inv
  prompt: If you achieve a completion on your 1st attempt, you will have earned…
  options:
    - 30 - 20 = 10 tokens
    - 30 - 8 = 22 tokens
    - 30 - 5 = 25 tokens
    - 30 - 2 = 28 tokens

bonus_survey_question3_inv: &q3_inv
  prompt: If you achieve a completion on your 3rd attempt, you will have earned…
  options:
    - 30 - 20 = 5 tokens
    - 30 - 24 = 6 tokens
    - 30 - 15 = 15 tokens
    - 30 - 6 = 24 tokens

bonus_survey_question4: &q4
  prompt: In the typing task, how often do most players reach the target score?
  options:
    - 20% of the time
    - 50% of the time
    - 80% of the time

bonus_survey_success: &success >
  <p>You're ready to complete the first version of the typing task!<br>To begin, continue to the next screen.</p>

bonus_survey_success_2: &success2 >
  <p>You're ready to complete the second version of the typing task!<br>To begin, continue to the next screen.</p>

bonus_suvey_failure: &failure >
  <p>Oops, you have provided at least one incorrect answer.</p>
  <p>To make sure you understand the game, please continue to re-read the instructions.</p>

bonus_instruction:
  instruction: 
    title: *i1
    info: *i2
    binary streak: *ig1
    continuous streak: *ig2
    binary: *ig3
    inverse streak: *ig4
  example: 
    title: [*bfm, *bfs, *bfm, *bff]
    header:
      - "<p class=instruction-title>In the 1st round, if you score <b><span id='current-number'></span></b> and the target score is <b><span id='target-number'></span></b>, you will see: </p>"
      - "<p class=instruction-title>Then you will see: </p>"
      - "<p class=instruction-title>In the 1st round, if you score <b><span id='current-number'></span></b> and the target score is <b><span id='target-number'></span></b>, you will see: </p>"
      - "<p class=instruction-title>Then you will see: </p>"
    binary streak:
      - "Current Streak: 1/3"
      - "Current Streak: 0/3"
    continuous streak:
      - "Current Streak: 1"
      - "Current Streak: 0"
    binary: 
      - "Bonus: +$0.10"
      - "Bonus: +$0.00"
  questions: [*q1, *q2, *q3, *q4]
  questions_inv: [*q1, *q2_inv, *q3_inv, *q4]
  randomize_order: true 
  data: 
    phase: bonus_instruction
  feedback_success: *success
  feedback_failure: *failure

bonus_instruction_2:
  instruction:
    title: *i1_2
    info: *i2_2
    binary streak: *ig1_2
    continuous streak: *ig2_2
    binary: *ig3_2
    inverse streak: *ig4_2
  example: 
    title: [*bfm, *bfs, *bfm, *bff]
    header:
      - "<p class=instruction-title>In the 1st round, if you score <b><span id='current-number'></span></b> and the target score is <b><span id='target-number'></span></b>, you will see: </p>"
      - "<p class=instruction-title>Then you will see: </p>"
      - "<p class=instruction-title>In the 1st round, if you score <b><span id='current-number'></span></b> and the target score is <b><span id='target-number'></span></b>, you will see: </p>"
      - "<p class=instruction-title>Then you will see: </p>"
    binary streak:
      - "Current Streak: 1/3"
      - "Current Streak: 0/3"
    continuous streak:
      - "Current Streak: 1"
      - "Current Streak: 0"
    binary: 
      - "Bonus: +$0.10"
      - "Bonus: +$0.00"
  questions: [*q1, *q2, *q3, *q4]
  questions_inv: [*q1, *q2_inv, *q3_inv, *q4]
  randomize_order: true 
  data: 
    phase: bonus_instruction
  feedback_success: *success2
  feedback_failure: *failure

debrief_page: &debrief >
  <p>Thank you for participating!</p>
  <p>In total, you won <b>${totalBonus}</b> tokens!</p>
  <br>
  <p>Within one week, you'll find out if you won the $100.00 bonus. To receive payment, please enter your Prolific PID in the space below, then continue and <strong>wait to be redirected to Prolific</strong>.</p>

debrief:
  type: survey
  button_label: Continue
  data: 
    phase: survey_questionaire

lastpage:
  type: text
  questions:
    - prompt: ""
      placeholder: pid
      name: "email"
      columns: 80
      required: true
  button_label: [CLICK HERE TO FINISH]
  preamble: *debrief